FROM python:3.12-slim

# RUN addgroup --system appgroup && adduser --system --no-create-home appuser -G appgroup
RUN groupadd -r appgroup && useradd -r -g appgroup appuser

WORKDIR /app

COPY /app/requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY /app/app.py .

EXPOSE  5000

RUN chown -R appuser:appgroup /app

USER appuser

CMD [ "python3","app.py" ]